
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUAL JAVASCRIPT LANGLE LANGLESLASH RANGLE STRING WORDhtml : elt htmlhtml : elt : WORDelt : JAVASCRIPTelt : LANGLE WORD opt_args RANGLE html LANGLESLASH WORD RANGLEopt_args : tag_argsopt_args : tag_args : WORD tag_argstag_args : WORD'
    
_lr_action_items = {'LANGLE':([0,2,3,5,12,16,],[1,-3,-4,1,1,-5,]),'WORD':([0,1,2,3,5,6,8,12,14,16,],[2,6,-3,-4,2,8,8,2,15,-5,]),'JAVASCRIPT':([0,2,3,5,12,16,],[3,-3,-4,3,3,-5,]),'RANGLE':([6,8,9,10,11,15,],[-7,-9,-6,12,-8,16,]),'LANGLESLASH':([2,3,5,7,12,13,16,],[-3,-4,-2,-1,-2,14,-5,]),'$end':([0,2,3,4,5,7,16,],[-2,-3,-4,0,-2,-1,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'opt_args':([6,],[10,]),'html':([0,5,12,],[4,7,13,]),'tag_args':([6,8,],[9,11,]),'elt':([0,5,12,],[5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> elt html','html',2,'p_html','html_parser.py',16),
  ('html -> <empty>','html',0,'p_html_empty','html_parser.py',21),
  ('elt -> WORD','elt',1,'p_elt_word','html_parser.py',25),
  ('elt -> JAVASCRIPT','elt',1,'p_elt_javascript','html_parser.py',36),
  ('elt -> LANGLE WORD opt_args RANGLE html LANGLESLASH WORD RANGLE','elt',8,'p_elt_tag','html_parser.py',40),
  ('opt_args -> tag_args','opt_args',1,'p_opt_args','html_parser.py',44),
  ('opt_args -> <empty>','opt_args',0,'p_opt_args_empty','html_parser.py',48),
  ('tag_args -> WORD tag_args','tag_args',2,'p_tag_args','html_parser.py',52),
  ('tag_args -> WORD','tag_args',1,'p_tag_args_last','html_parser.py',56),
]
